# Horaires des events
schedule:
  spleef:
    - "18:00"
    - "22:00"

# Spawn du lobby général
event-lobby:
  world: Event
  x: -23.65
  y: -8.0
  z: 0.79
  yaw: 73.7
  pitch: 13.1

# Spawns spécifiques à chaque event
event-spawns:
  spleef:
    world: Event
    x: 100.0
    y: 64.0
    z: 200.0
    yaw: 180.0
    pitch: 0.0

