# Horaires des events
schedule:
  RANDOM_EVENT:
    - "18:00"

lobby-wait-time: 5  # en minutes

rewards:
  '1':
    1:
      displayname: "&e2000 PE"
      lore: "Clique pour 2000PE"
      reward: eco give %player% 2000
    2:
      displayname: "Skills points"
      lore: ""
      reward: giveskills %player% 2
    3:
      displayname: "&e2000 da"
      lore: "Clique pour 2000PE"
      reward: eco give %player% 2000

  '2': eco give %player% 1200
  '3': eco give %player% 800
  default: eco give %player% 500


# Spawn du lobby général
event-lobby:
  world: Event
  x: -23.65
  y: -8.0
  z: 0.79
  yaw: 73.7
  pitch: 13.1

# Spawns spécifiques à chaque event
event-spawns:
  spleef:
    world: Event
    x: 100.0
    y: 64.0
    z: 200.0
    yaw: 180.0
    pitch: 0.0

